### ISSUE TITLE
cannot open file ~/.cache/oh-my-earth/momentumdash.random.jpg

### ISSUE THREAD

**Issue by zxj5470** [ujnzxw/oh-my-earth#10]
OS: Ubuntu 16.04.3
Unity 
have installed dependencies .....
and run:
`oh-my earth`
```
Updating momentumdash image...
Traceback (most recent call last):
  File "/usr/local/bin/oh-my-earth", line 34, in <module>
    main()
  File "/usr/local/bin/oh-my-earth", line 28, in main
    MomentumdashManager().run()
  File "/media/zh/SharedFiles/git/oh-my-earth/manage_momentum.py", line 48, in run
    self.get_bg_picture()
  File "/media/zh/SharedFiles/git/oh-my-earth/manage_momentum.py", line 39, in get_bg_picture
    urllib.urlretrieve(imgurl, momentumdash_output_file)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: '/home/zxj5470/.cache/oh-my-earth/momentumdash.random.jpg'
```

**Comment by gmftbyGMFTBY** [comment]
先创建目录 ~/.cache/oh-my-earth
