### ISSUE TITLE
Note: An error when move earth code to manage_earth.py

### ISSUE THREAD

**Issue by ujnzxw** [ujnzxw/oh-my-earth#4]
ERROR:
```
Updating...
Latest version: 2017/06/03 02:30:00 GMT
Offset version: 2017/06/03 02:30:00 GMT

Downloading tiles: 0/64 completed
Traceback (most recent call last):
  File "./run.py", line 17, in <module>
    main()
  File "./run.py", line 14, in main
    e.run()
  File "/home/xzhao027/Code/oh-my-earth/manage_earth.py", line 127, in run
    res = p.map(download_chunk, product(range(level), range(level), (requested_time,)))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
TypeError: download_chunk() takes exactly 2 arguments (1 given)
```

**Comment by ujnzxw** [comment]
Root cause:
==========
I put download_chunk method into class EarthManager() and called it in mutilprocess:
`res = p.map(self.download_chunk, product(range(level), range(level), (requested_time,)))`

the problem is that multiprocessing must pickle things to sling them among processes, and bound methods are not picklable

Refer to:
======
[Python Can't pickle type 'instancemethod' 问题 ](https://blog.tankywoo.com/2015/09/06/cant-pickle-instancemethod.html)

[Can't pickle <type 'instancemethod'> when using python's multiprocessing Pool.map()](https://stackoverflow.com/questions/1816958/cant-pickle-type-instancemethod-when-using-pythons-multiprocessing-pool-ma)
